version: '3'

############################################################################
# INFO:

# Services:
#  portainer
#  apache2 (letsencrypt/RevProxy/fail2ban
#  proftpd (/FTP/SMB/homepage)
#  mySQL-Datenbank (Logging/FHEM-Logging/Filmdatenbank)
#  phpMyAdmin (WebUI für mySQL)
#  Debian Jessie zum Spielen
#  FHEM
#  FHEM-SONOS
#  FHEM-Alexa
#  TVheadend mit OSCAM für HDTV (TV>IP)

# Fagen/Zusatzinfos:
#  privileged --> alle USB Geräte werden übergeben
#  lsusb -v | grep Serial
#  ls -l /dev/serial/by-id

############################################################################
# SICHERHEIT & PORTS:
#############################################################################

# Sicherheitskonzept Netzwerk/Internet:
# In NAS zusätzlich zu https noch http aktivieren
# Anfragen über Internet über ReverseProxy und https
# Interne Umleitung (Netzwerk) auf http

# Modem Portweiterleitung anpassen:
# alle eingehenden Verbindungen zu ReverseProxy (Port 443) weiter leiten

# PORTS:
#  http             80
#  https            443
#  Portainer        9000
#  mySQL            3306
#  phpMyAdmin       8080
#  Alexa            3000

#  FHEM             8083
#    WebAPI         8089
#    WebAlexa       8090
#    Telnet         7072

#  TVheadend        9981
#    htsp IP TV     9982
#    OSCAM          8888

#  FTP              20 21           (Filezilla)
#    PassivePorts   60000-60100     (Browser Ports)
#    Samba          137/udp 138/udp 139 445


############################################################################
# USER & PASSWÖRTER:
#############################################################################

# mySQL:
#  root
#    User:  root
#    Pwd:   root
#  FHEM
#    User:  fhemuser
#    Pwd:   fhemuser
#  Kodi
#    User:  kodi
#    Pwd:   kodi

# FTP
#  Admin
#    User:  admin
#    Pwd:   admin
#    URL:   ftp://admin:admin@192.168.X.X
#  FHEM
#    User:  fhem
#    Pwd:   fhem
#    URL:   ftp://fhem:fhem@192.168.X.X
#  IP Kamera
#    User:  camera
#    Pwd:   camera
#    URL:   ftp://camera:camera@192.168.X.X

# SMB
#  Kodi
#    User:  kodi
#    Pwd:   kodi

#  USB-Geräte übergeben:
#    ttyUSB0: SIGNALduino
#    ttyUSB1: Jeelink 868,35MHz LaCrosse (Temp./Luftfeuchtigkeit)
#    ttyUSB2: CUL 433MHz (Funksteckdosen)
#    ttyUSB3: CUL 868,35MHz SlowRF (billige Sensoren und Aktoren)
#    ttyUSB4: CUL 868,3MHz HomeMatic

# FHEM API (extern)
#  User:    fhemapi
#  Pwd:     fhemapi
#? Proxy:   /fhem_api
#  Port:    8089

# FHEM API (IFTTT)
#  User:    fhemifttt
#  Pwd:     fhemifttt
#  Proxy:   /fhem_ifttt
#? Port:    8090

# FHEM Alexa (Smart Home Skill)
#  User:    fhemalexa
#  Pwd:     fhemalexa
#  Proxy:   /fhem_alexa
#  Port:    3000

# TVheadend:
#  Admin
#    User:  tvhadmin
#    Pwd:   tvhadmin
#  User
#    User:  tvhuser
#    Pwd:   tvhuser
#  OSCAM
#    User:  tvhoscam
#    Pwd:   tvhoscam

############################################################################
############################################################################
# VOLUMES:
############################################################################
############################################################################

volumes:

############################################################################
# Volumes: TVheadend
############################################################################

    tvh.config:
        driver: local

    tvh.recordings:
        driver: local

############################################################################
# Volumes: SSL Zertifikate
############################################################################

    ssl.cert:
        driver: local

############################################################################
# Volumes: FTP Daten
############################################################################

    ftp.camera:
        driver: local

    ftp.fhem:
        driver: local

############################################################################
############################################################################
# SERVICES:
############################################################################
############################################################################

services:

############################################################################
# Service: Apache2
############################################################################

    apache2:
        container_name: apache2
        restart: always
        expose:
            - "443"
            - "80"
        ports:
            - "443:443"
            - "80:80"
        build: apache2
        volumes:
            - ./apache2/entrypoint.sh:/entrypoint.sh
            - ./apache2/data/html/:/var/www/html/
            - ./apache2/data/logs/apache2/:/var/log/apache2/
            - ./apache2/data/logs/fail2ban/fail2ban.log:/var/log/fail2ban.log
            - ./apache2/data/config/proxy/<website>.conf:/etc/apache2/sites-available/<website>.conf
            - ./apache2/data/config/fail2ban/apache2.local:/etc/fail2ban/jail.d/apache2.local
            - ./apache2/data/config/fail2ban/action.d/docker-ban.conf:/etc/fail2ban/action.d/docker-ban.conf
            - ssl.cert:/etc/letsencrypt
        network_mode: "bridge"

############################################################################
# Service: Proftpd
############################################################################

# Cloud (FTP/SMB/NFS) für:
#  Kodi Config (Quellen für Filme/Serien/IPTV/Fotos anpassen)
#  Aufnahmen von TVheadend
#  IP-Kamera
#  Kalender (Abfall)

    proftpd:
        container_name: proftpd
        restart: always
        expose:
            - "20"
            - "21"
            - "139"
            - "445"
        ports:
            - "20:20"
            - "21:21"
            - "60000-60100:60000-60100"
            - "139:139"
            - "445:445"
        build: proftpd
        volumes:
            - ./proftpd/entrypoint.sh:/entrypoint.sh
            - ./proftpd/data/logs/proftpd/:/var/log/proftpd/
            - ./proftpd/data/config/ftp/proftp-custom.conf:/etc/proftpd/conf.d/proftp-custom.conf
            - ./proftpd/data/config/ftp/tls-custom.conf:/etc/proftpd/conf.d/tls-custom.conf
            - ./proftpd/data/logs/smb/:/var/log/samba/
            - ./proftpd/data/config/smb/smb-custom.conf:/etc/samba/smb.conf
            - ssl.cert:/etc/letsencrypt
            - tvh.recordings:/var/www/ftp/recordings/
            - ftp.camera:/var/www/ftp/camera/
            - ftp.fhem:/var/www/ftp/fhem/
        network_mode: "bridge"

############################################################################
# Service: Portainer
############################################################################

# docker-compose WebUI testen

    portainer:
        container_name: portainer
        restart: always
        expose:
            - "9000"
        ports:
            - "9000:9000"
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "bridge"

############################################################################
# Service: MySQL
############################################################################

# Fhem DBlog:
#  jedes FHEM devices mit event on change bzw. update reading definieren
#  (Hält die Datenbank klein)

# Für Kodi Filmdatenbank vorbereiten

    mysql:
        container_name: mysql
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        image: mysql/mysql-server:latest
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql/fhem-init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/kodi-init.sql:/docker-entrypoint-initdb.d/kodi-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
        network_mode: "bridge"

############################################################################
# Service: phpMyAdmin
############################################################################

    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        expose:
            - "80"
        ports:
            - "8080:80"
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=pwd
        links:
            - "mysql:mysql"
        network_mode: "bridge"
        depends_on:
            - "mysql"

############################################################################
# Service: MQTT
############################################################################

#    mqtt:
#        container_name: fhem_mqtt
#        restart: always
#        expose:
#            - "1883"
#        ports:
#            "1833:1833"
#        build: fhem_mqtt
#        volumes:
#        network_mode: "bridge"
#        depends_on:
#            - "apache2"

############################################################################
# Service: FHEM SONOS
############################################################################

# Multicast     Sonos benutzt 239.255.255.250/1900
# Je nachdem wie Du das Netz segmentiert hast, kannst Du IGMP oder einen Multicast/Bonjour-Proxy einsetzen

#    sonos:
#        container_name: fhem_sonos
#        restart: always
#        build: fhem_sonos
#        volumes:
#            - ./fhem_sonos/entrypoint.sh:/entrypoint.sh
#        links:
#        hostname: fhem_sonos
#        network_mode: "host"
#        networks:
#            net_host:
#                ipv4_address: 192.168.X.X

############################################################################
# Service: FHEM Alexa
############################################################################

    alexa:
        container_name: fhem_alexa
        restart: always
        expose:
            - "3000"
        ports:
            - "3000:3000"
        build: fhem_alexa
        volumes:
            - ./fhem_alexa/entrypoint.sh:/entrypoint.sh
            - ./fhem_alexa/data/config/config.json:/config/config.json
            - ssl.cert:/etc/letsencrypt
        network_mode: "bridge"
        depends_on:
            - "apache2"
            - "fhem"

############################################################################
# Service: FHEM
############################################################################

    fhem:
        container_name: fhem
        restart: always
        expose:
            - "8083"
            - "8089"
            - "8090"
            - "7072"
        ports:
            - "8083:8083"
            - "8089:8089"
            - "8090:8090"
            - "7072:7072"
        build: fhem
        devices:
            - /dev/lirc0:/dev/lirc0
            - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_GPIOPINS-if00-port0:/dev/ttyUSB0
            - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9M9DV3R-if00-port0:/dev/ttyUSB1
            - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_CUL433MH-if00-port0:/dev/ttyUSB2
#            - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_CUL868MH-if00-port0:/dev/ttyUSB3
#            - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_CUL?????-if00-port0:/dev/ttyUSB4
        volumes:
            - ./fhem/entrypoint.sh:/entrypoint.sh
            - ./fhem/log/:/opt/fhem/log/
            - ./fhem/backup/:/opt/fhem/backup/
            - ./fhem/data/fhem.cfg:/opt/fhem/fhem.cfg
            - ./fhem/data/kal_abfall.ics:/opt/fhem/kal_abfall.ics
            - ./fhem/data/FHEM/controls.txt:/opt/fhem/FHEM/controls.txt
            - ./fhem/data/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
            - ./fhem/data/FHEM/hol_nrw.holiday:/opt/fhem/FHEM/hol_nrw.holiday
            - ./fhem/data/contrib/dblog/db.conf:/opt/fhem/contrib/dblog/db.conf
            - ./fhem/data/www/gplot/:/opt/fhem/data/www/gplot/
            - ./fhem/data/www/images/default/:/opt/fhem/data/www/images/default/
            - ./fhem/data/lirc/lircd.conf:/etc/lirc/lircd.conf
            - ./fhem/data/lirc/hardware.conf:/etc/lirc/hardware.conf
            - ./fhem/data/lirc/lircrc:/opt/fhem/lircrc
            - ftp.camera:/var/www/ftp/camera/
            - ftp.fhem:/var/www/ftp/fhem/
#        links:
#            - "mysql:mysql"
#            - "alexa:alexa"
        network_mode: "bridge"
#        networks:
#            - fhem_bridge
        depends_on:
            - "mysql"
            - "proftpd"
#            - "sonos"

############################################################################
# Service: TVheadend mit OSCAM
############################################################################

    tvheadend:
        container_name: tvheadend
        restart: always
        expose:
            - "9981"
            - "9982"
            - "8888"
        ports:
            - "9981:9981"
            - "9982:9982"
            - "8888:8888"
        build: tvheadend
        privileged: true
#        devices:
#            - /dev/serial/by-id/usb-Argolis_BV_Smartreader2_plus_HDPLUS-if00-port0:/dev/ttyUSB0
        volumes:
            - ./tvheadend/entrypoint.sh:/entrypoint.sh
            # Volumes in Container mounten
            - tvh.config:/config
            - tvh.recordings:/recordings
        network_mode: "bridge"
